public abstract class AbstractClassParent {
    //When some mehtods ouput are same and others are different,then we should use Abstract Class
    public void Show(){//Method Declaration
        System.debug('Salesforce');//Body
    }
    //Abstract method won't contain the body and it must contain abstract keyword in the method declaration
    Public abstract Void Message();//Method Declaration
    
}