public with sharing class CC3 {

    public String result { get; set; }

    public String num2 { get; set; }

    public String num1 { get; set; }

    public PageReference division() {
        return null;
    }


    public PageReference product() {
        return null;
    }


    public PageReference diff() {
        return null;
    }


    public PageReference addition() {
        return null;
    }

}