@isTest//annotation that conveys to ARE
     public class RectangleTest {
         //in test class we use two keywords static and testMethod 
      public static testMethod void main(){
         //create an object
         //className obj_name= new ClassName();
      Rectangle.getCount();
      Rectangle rec1 = new Rectangle(11,12);//calling constructor
          Rectangle.getCount();
          rec1.calcArea();
          Rectangle rec2 = new Rectangle();
           Rectangle rec3 = new Rectangle();
           Rectangle rec4 = new Rectangle();
           Rectangle rec5 = new Rectangle();
          Rectangle.getCount();
      }
}